// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from generateprime.djinni

#include "NativeGeneratePrime.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeGeneratePrime::NativeGeneratePrime() : ::djinni::JniInterface<::generateprime::GeneratePrime, NativeGeneratePrime>("com/mycompany/generateprime/GeneratePrime$CppProxy") {}

NativeGeneratePrime::~NativeGeneratePrime() = default;


CJNIEXPORT void JNICALL Java_com_mycompany_generateprime_GeneratePrime_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::generateprime::GeneratePrime>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_mycompany_generateprime_GeneratePrime_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::generateprime::GeneratePrime::create();
        return ::djinni::release(::djinni_generated::NativeGeneratePrime::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_com_mycompany_generateprime_GeneratePrime_00024CppProxy_native_1generatePrime(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_a)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::generateprime::GeneratePrime>(nativeRef);
        auto r = ref->generate_prime(::djinni::I32::toCpp(jniEnv, j_a));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
