// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from generateprime.djinni

#pragma once

#include "djinni_support.hpp"
#include "generate_prime.hpp"

namespace djinni_generated {

class NativeGeneratePrime final : ::djinni::JniInterface<::generateprime::GeneratePrime, NativeGeneratePrime> {
public:
    using CppType = std::shared_ptr<::generateprime::GeneratePrime>;
    using CppOptType = std::shared_ptr<::generateprime::GeneratePrime>;
    using JniType = jobject;

    using Boxed = NativeGeneratePrime;

    ~NativeGeneratePrime();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeGeneratePrime>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeGeneratePrime>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeGeneratePrime();
    friend ::djinni::JniClass<NativeGeneratePrime>;
    friend ::djinni::JniInterface<::generateprime::GeneratePrime, NativeGeneratePrime>;

};

}  // namespace djinni_generated
