// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from generateprime.djinni

#import <Foundation/Foundation.h>
@class GPGeneratePrime;


@interface GPGeneratePrime : NSObject

+ (nullable GPGeneratePrime *)create;

- (int32_t)generatePrime:(int32_t)a;

@end
