// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from generateprime.djinni

#import "GPGeneratePrime+Private.h"
#import "GPGeneratePrime.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface GPGeneratePrime ()

- (id)initWithCpp:(const std::shared_ptr<::generateprime::GeneratePrime>&)cppRef;

@end

@implementation GPGeneratePrime {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::generateprime::GeneratePrime>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::generateprime::GeneratePrime>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable GPGeneratePrime *)create {
    try {
        auto objcpp_result_ = ::generateprime::GeneratePrime::create();
        return ::djinni_generated::GeneratePrime::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (int32_t)generatePrime:(int32_t)a {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->generate_prime(::djinni::I32::toCpp(a));
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto GeneratePrime::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto GeneratePrime::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<GPGeneratePrime>(cpp);
}

}  // namespace djinni_generated

@end
