// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from generateprime.djinni

#include "generate_prime.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class GPGeneratePrime;

namespace djinni_generated {

class GeneratePrime
{
public:
    using CppType = std::shared_ptr<::generateprime::GeneratePrime>;
    using CppOptType = std::shared_ptr<::generateprime::GeneratePrime>;
    using ObjcType = GPGeneratePrime*;

    using Boxed = GeneratePrime;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

