// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from generateprime.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace generateprime {

class GeneratePrime {
public:
    virtual ~GeneratePrime() {}

    static std::shared_ptr<GeneratePrime> create();

    virtual int32_t generate_prime(int32_t a) = 0;
};

}  // namespace generateprime
